import {
  BarChart3,
  BookOpen,
  Calendar,
  CreditCard,
  FileSignature,
  FolderOpen,
  Globe,
  KeyRound,
  LayoutList,
  Share2,
  Mail,
  MessageSquare,
  Palette,
  Receipt,
  Search,
  Sheet,
  Users,
  Workflow,
  type LucideIcon,
} from "lucide-react";
import type { ToolName } from "@/data/types";

// Generic icons only — no brand marks.
export const TOOL_ICONS: Record<ToolName, LucideIcon> = {
  HubSpot: Users,
  Gmail: Mail,
  Notion: BookOpen,
  Stripe: CreditCard,
  Slack: MessageSquare,
  "Google Drive": FolderOpen,
  "Google Sheets": Sheet,
  "Google Calendar": Calendar,
  LinkedIn: Share2,
  Canva: Palette,
  Webflow: Globe,
  "Google Analytics": BarChart3,
  Linear: LayoutList,
  Zapier: Workflow,
  Xero: Receipt,
  DocuSign: FileSignature,
  "1Password": KeyRound,
  Perplexity: Search,
};
