import {
  BarChart3,
  BookOpen,
  Calendar,
  CreditCard,
  FileSignature,
  FolderOpen,
  Globe,
  KeyRound,
  LayoutList,
  Mail,
  MessageSquare,
  Palette,
  Receipt,
  Search,
  Share2,
  Sheet,
  Users,
  Workflow,
  type LucideIcon,
} from "lucide-react";
import type { ToolName } from "@/data/types";

// Generic icons only — no brand marks.
export const TOOL_ICONS: Record<ToolName, LucideIcon> = {
  HubSpot: Users,
  Outlook: Mail,
  "Outlook Calendar": Calendar,
  Teams: MessageSquare,
  SharePoint: FolderOpen,
  Excel: Sheet,
  Planner: LayoutList,
  "Power Automate": Workflow,
  Notion: BookOpen,
  Stripe: CreditCard,
  Fortnox: Receipt,
  Scrive: FileSignature,
  LinkedIn: Share2,
  Canva: Palette,
  Webflow: Globe,
  "Google Analytics": BarChart3,
  "1Password": KeyRound,
  Perplexity: Search,
};
